
export const productData = [
    {
        id: 1,
        title: "Apple",
        subtitle: "Green Apple",
        text: "A healthy, sweet fruit...",
        image: "images/apple.jpg",
        category: "fruit",
        rating: 3.8,
        reviews: 521,
        price: 408,
        originalPrice: 1000,
        discountPercent: 59
    },
    {
        id: 2,
        title: "Chocolate",
        subtitle: "Mix Chocolate",
        text: "A sweet, delicious treat...",
        image: "images/chol.jpg",
        category: "chocolate",
        rating: 3.3,
        reviews: 511,
        price: 608,
        originalPrice: 1500,
        discountPercent: 59
    },
    {
        id: 3,
        title: "Frock",
        subtitle: "Girl Frock",
        text: "A comfortable and stylish dress...",
        image: "images/frock.jpg",
        category: "frock",
        rating: 3.8,
        reviews: 601,
        price: 500,
        originalPrice: 2000,
        discountPercent: 79
    },
    {
        id: 4,
        title: "Red Apple",
        subtitle: "Red Apple",
        text: "A crunchy red apple...",
        image: "images/fruit.jpg",
        category: "fruit",
        rating: 3.7,
        reviews: 501,
        price: 308,
        originalPrice: 500,
        discountPercent: 69
    },
    {
        id: 5,
        title: "Long Frock",
        subtitle: "Girl Frock",
        text: "Stylish long frock...",
        image: "images/frock1.jpg",
        category: "frock",
        rating: 3.5,
        reviews: 400,
        price: 300,
        originalPrice: 3000,
        discountPercent: 60
    },
    {
        id: 6,
        title: "Jens",
        subtitle: "Men Jens",
        text: "Durable denim pants...",
        image: "images/jens.jpg",
        category: "jens",
        rating: 4.8,
        reviews: 401,
        price: 1000,
        originalPrice: 5000,
        discountPercent: 59
    },
    {
        id: 7,
        title: "Milk",
        subtitle: "Cow Milk",
        text: "A nutritious white liquid cows....",
        image: "images/milk.jpg",
        category: "milk",
        rating: 3.2,
        reviews: 521,
        price: 400,
        originalPrice: 1000,
        discountPercent: 59
    },
    {
        id: 8,
        title: "Juice",
        subtitle: "Orange Juice",
        text: "Refreshing and full of vitamins...",
        image: "images/juice.jpg",
        category: "fruit",
        rating: 3.0,
        reviews: 701,
        price: 608,
        originalPrice: 2000,
        discountPercent: 59
    },
    {
        id: 9,
        title: "Juice",
        subtitle: "Mix Juice",
        text: "Refreshing and full of vitamins...",
        image: "images/juice2.jpg",
        category: "fruit",
        rating: 3.8,
        reviews: 521,
        price: 408,
        originalPrice: 1000,
        discountPercent: 59
    },
    {
        id: 10,
        title: "Noodle",
        subtitle: "Chain Noodle",
        text: "Tasty and quick-cooking noodles....",
        image: "images/noodle.jpg",
        category: "fast food",
        rating: 5.8,
        reviews: 821,
        price: 7000,
        originalPrice: 15000,
        discountPercent: 80
    },
    {
        id: 11,
        title: "jens",
        subtitle: "Lady Jens",
        text: "Durable and trendy pants made...",
        image: "images/jens3.jpg",
        category: "jens",
        rating: 3.8,
        reviews: 721,
        price: 3000,
        originalPrice: 9000,
        discountPercent: 75
    },
    {
        id: 12,
        title: "Shoes",
        subtitle: "Sport Shoes",
        text: "Comfortable and stylish shoes...",
        image: "images/shoes.jpg",
        category: "shoes",
        rating: 6.8,
        reviews: 800,
        price: 1000,
        originalPrice: 7000,
        discountPercent: 70
    },
    {
        id: 13,
        title: "Milk",
        subtitle: "Malae Milk",
        text: "Refreshing and full of vitamins...",
        image: "images/milk3.jpg",
        category: "milk",
        rating: 3.7,
        reviews: 301,
        price: 295,
        originalPrice: 500,
        discountPercent: 59
    },
    
];
